### ISSUE TITLE
Failed to get Agreement Details

### ISSUE THREAD

**Issue by H34D** [nevermined-io/sdk-js#282]
## Describe the bug
If i try to retrieve agreement details like this:

```
        agreement = await nvm.agreements.getAgreement(
            event.returnValues._agreementId
        );
```

it greets me with an error message like this:

```
TypeError: Cannot read properties of undefined (reading 'returnValues')
    at AgreementStoreManager.<anonymous> (/xxx/odules/@nevermined-io/nevermined-sdk-js/src/keeper/contracts/managers/AgreementStoreManager.ts:49:16)
    at Generator.next (<anonymous>)
    at fulfilled (/xxxdules/@nevermined-io/nevermined-sdk-js/dist/node/keeper/contracts/managers/AgreementStoreManager.js:5:58)

``` 

##  To Reproduce
1. Connect to mumbai with any given sdk verison
2. Query agreement details with agreement id

## Expected behavior
It returns agreement details

**Comment by H34D** [comment]
fixed with #284
